//테이블 쿼리문
CREATE TABLE member(
                       id bigint not null  generated by default as identity,
                       name varchar(20),
                       nickname varchar(10),
                       primary key(id) );

CREATE TABLE write(
                      id bigint not null  generated by default as identity,
                      title varchar(30),
                      content varchar(1000),
                      member_id bigint,
                      primary key(id));

